### ISSUE TITLE
com.intellij.openapi.project.IndexNotReadyException

### ISSUE THREAD

**Issue by artspb** [Haehnchen/idea-php-oxid-plugin#10]
I got a couple of them. You can use `com.intellij.openapi.project.DumbService#isDumb()` to check whether it's possible to use indices or not.

```
Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation

com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:722)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:671)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:654)
	at com.intellij.psi.stubs.StubIndexImpl.doProcessStubs(StubIndexImpl.java:346)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:327)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:146)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:135)
	at com.jetbrains.php.PhpIndexImpl.getByName(PhpIndexImpl.java:565)
	at com.jetbrains.php.PhpIndexImpl.getByFQN(PhpIndexImpl.java:545)
	at com.jetbrains.php.PhpIndexImpl.getClassesByFQN(PhpIndexImpl.java:575)
	at com.jetbrains.php.PhpIndexImpl.getAnyByFQN(PhpIndexImpl.java:591)
	at fr.adrienbrault.idea.symfony2plugin.util.PhpElementsUtil.getClassInterface(PhpElementsUtil.java:461)
	at de.espend.idea.oxid.utils.OxidUtil.getPseudoClassOverwrites(OxidUtil.java:72)
	at de.espend.idea.oxid.utils.OxidUtil$1.run(OxidUtil.java:218)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:907)
	at de.espend.idea.oxid.utils.OxidUtil.buildClassMetadataFile(OxidUtil.java:215)
	at de.espend.idea.oxid.OxidProjectComponent$1$1.run(OxidProjectComponent.java:53)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:757)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:181)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:587)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:137)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Haehnchen** [comment]
done
