### ISSUE TITLE
Plugin is not usable with PHPStorm 2018

### ISSUE THREAD

**Issue by patrikkernke** [Haehnchen/idea-php-oxid-plugin#15]
Erroroutput:
```
Argument for @NotNull parameter 'files' of com/intellij/openapi/command/WriteCommandAction.<init> must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'files' of com/intellij/openapi/command/WriteCommandAction.<init> must not be null
	at com.intellij.openapi.command.WriteCommandAction.$$$reportNull$$$0(WriteCommandAction.java)
	at com.intellij.openapi.command.WriteCommandAction.<init>(WriteCommandAction.java)
	at de.espend.idea.oxid.utils.OxidUtil$1.<init>(OxidUtil.java:227)
	at de.espend.idea.oxid.utils.OxidUtil.buildClassMetadataFile(OxidUtil.java:227)
	at de.espend.idea.oxid.OxidProjectComponent$1.run(OxidProjectComponent.java:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Thank you for such a great plugin! I hope the error will be fixed quick!

**Comment by pvanhemmen** [comment]
Can confirm this issue

**Comment by herieth** [comment]
Hi Daniel,
can confirm the issue too. Will there be a fix in the foreseeable future?
Thanks for your work!

**Comment by nymo** [comment]
@Haehnchen 
any news on this? What is the planned fix? PhpStorm 2018.2 was already released. Would be great to use this plugin in the new PhpStorm Version.

**Comment by patrikkernke** [comment]
@Haehnchen 
Would love to hear an answer :) I know it is a lot work to mantain projects like this one, but it would be great to know if there are a plans for bugfixing errors or to drop the plugin.

**Comment by czkit** [comment]
Hi Daniel, i can confirm the issue too :(

**Comment by alfredbez** [comment]
I get two Exceptions: the one from the first comment and this one:
```
Argument for @NotNull parameter 'files' of com/intellij/openapi/command/WriteCommandAction.<init> must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'files' of com/intellij/openapi/command/WriteCommandAction.<init> must not be null
	at com.intellij.openapi.command.WriteCommandAction.$$$reportNull$$$0(WriteCommandAction.java)
	at com.intellij.openapi.command.WriteCommandAction.<init>(WriteCommandAction.java)
	at de.espend.idea.oxid.utils.OxidUtil$1.<init>(OxidUtil.java:227)
	at de.espend.idea.oxid.utils.OxidUtil.buildClassMetadataFile(OxidUtil.java:227)
	at de.espend.idea.oxid.OxidProjectComponent$2.run(OxidProjectComponent.java:60)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by georgbez** [comment]
May I ask you to take a look at this problem.
It also occurs here with PHPStorm 2021.3.3.

If it helps we can do a debug session sometime?!
Thanks already!

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'files' of com/intellij/openapi/command/WriteCommandAction.<init> must not be null
	at com.intellij.openapi.command.WriteCommandAction.$$$reportNull$$$0(WriteCommandAction.java)
	at com.intellij.openapi.command.WriteCommandAction.<init>(WriteCommandAction.java)
	at de.espend.idea.oxid.utils.OxidUtil$1.<init>(OxidUtil.java:227)
	at de.espend.idea.oxid.utils.OxidUtil.buildClassMetadataFile(OxidUtil.java:227)
	at de.espend.idea.oxid.OxidProjectComponent$1.run(OxidProjectComponent.java:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:436)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:120)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:496)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
	
```

**Comment by patrikkernke** [comment]
No reaction after 5 years :)
